services:
  flask_db:
    build: .
    volumes:
      - .:/usr/src/
    environment:
      - TZ=Asia/Taipei
    env_file:
      - .env
    ports:
      - 5000:5000
    working_dir: /usr/src
    command: bash -c "python main.py"